### ISSUE TITLE
CHERI branch still has 2-byte ifetch granularity

### ISSUE THREAD

**Issue by jrtc27** [CTSRD-CHERI/Toooba#7]
Whilst this seems like a good idea and should probably be upstreamed, it introduces additional divergence between CHERI-Toooba and vanilla Toooba, which will be problematic when doing any future PPA analysis. The changes should be reverted on the CHERI branch until such time as they are upstreamed and looped back in.

**Comment by PeterRugg** [comment]
Just wanted to bump this: is this still the case? Might not be quite so significant given some of the other divergences but we should keep it in mind and maybe mention it in the report.

**Comment by jrtc27** [comment]
Did we not upstream it?

**Comment by PeterRugg** [comment]
https://github.com/bluespec/Toooba/pull/17 ?

**Comment by jrtc27** [comment]
Yeah, that one. So I guess we can close this with a satisfactory resolution :)
